language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev redis-server
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=geoip.test_settings
install:
  - pip install -e . --use-mirrors
  - pip install -r requirements/tests.txt Django==$DJANGO --use-mirrors
before_script:
  - flake8 --exclude=migrations --ignore="F403" geoip
script:
  - coverage run --branch --source=geoip `which django-admin.py` test geoip
  - coverage report --omit="geoip/test*,geoip/migrations/*,geoip/management/*"
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.3.7
    - python: "3.3"
      env: DJANGO=1.4.10
branches:
  only:
    - master
    - development
after_success: coveralls
